version: '3.9'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDISPORT}:6379"
    volumes:
      - ./cache:/var/lib/redis/data
    networks:
      - saime
  app:
    image: gcr.io/saime-status/saime-status:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile.${ENV}
    container_name: app
    ports:
      - "${PORT}:3000"
    networks:
      - saime
    links:
      - redis
    depends_on:
      - redis
    environment:
      - ENV=${ENV}
      - GOOGLE_APPLICATION_CREDENTIALS=.gcp/credentials.json

volumes:
  app:
  redis:

networks:
  saime:
    driver: bridge