version: '3.9'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/var/lib/redis/data
    networks:
      - saime
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - saime
    links:
      - redis
    depends_on:
      - redis

volumes:
  app:
  redis:

networks:
  saime:
    driver: bridge