version: '3.9'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDISPORT}:6379"
    volumes:
      - ./cache:/var/lib/redis/data
    networks:
      - saime
  app:
    image: gcr.io/saime-status/saime-status:latest
    build: .
    ports:
      - "${PORT}:3000"
    networks:
      - saime
    links:
      - redis
    depends_on:
      - redis

volumes:
  app:
  redis:

networks:
  saime:
    driver: bridge