FROM golang:latest AS builder

# Set up the working directory
WORKDIR /app

# Install dependencies
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

# Build the application
RUN GOOS=linux GOARCH=amd64 go build -o /main src/cmd/main.go

# Run the application into a smaller container
FROM alpine

COPY --from=builder app/.env .
COPY --from=builder app/.gcp/ ./.gcp
COPY --from=builder /main .

EXPOSE 3000

ENTRYPOINT ["/main"]