FROM golang:latest AS builder

# Set up the working directory
WORKDIR /app

# Install Air
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

# Install dependencies
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

# Expose container port
EXPOSE 3000

# Run the application
CMD ["air"]